### ISSUE TITLE
Tema la tête du bordel

### ISSUE THREAD

**Issue by juliendechaud** [Woodlutins/MachinePingu#1]
# Bonjour,
J'aime beaucoup votre projet, cependant je trouve la structure du code source **immonde**. De plus, quand j'ai montrer l'interface à ma grand-mère, elle est partie **rejoindre tonton Johnny**. :suspect:

Merci d'avance pour votre retour,

_Un grand fan._:shipit:

**Comment by Woodlutins** [comment]
I dont speak French sowwy

**Comment by juliendechaud** [comment]
# Hello,
I really like your project, however I find the structure of the source code ugly. Moreover, when I showed the interface to my grandmother, she left to join Uncle Johnny. :suspect:

Thank you in advance for your return,

A big fan.:shipit:

**Comment by Woodlutins** [comment]
Oh yes thank you for your inspiring comments, its a passion work so I dont have much time to do it, but I'm currently trying to improve the interface and the global code.

Xoxo

Woodlutins 31m25 🧄

**Comment by juliendechaud** [comment]
ok boiii, go to make a pull request my man
